spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: IES_DEV
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: IES_DEV
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true