server:
  port: 3333
spring:
  application:
    name: GATEWAY-API
zuul:
  prefix: /ms
  routes:
    price:
      path: /api1/**
      serviceId: STOCK-PRICE-API
    calc:
      path: /api2/**
      serviceId: STOCK-CALC-API